name: "Run load tests"
description: "Runs load tests against an API endpoint"
inputs:
   api-endpoint:
     required: true
     description: "The API endpoint to run load tests against"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 20

    - run: npm i artillery -g
      shell: bash

    - name: Execute load tests
      shell: bash
      run: artillery run loadtest/load-test.yml --target "${{ inputs.api-endpoint }}"