build-GetProductFunctionX86:
	dotnet publish GetProduct/GetProduct.csproj -c Release -r linux-x64 --self-contained -o $(ARTIFACTS_DIR)

build-GetProductsFunctionX86:
	dotnet publish GetProducts/GetProducts.csproj -c Release -r linux-x64  --self-contained -o $(ARTIFACTS_DIR)

build-PutProductFunctionX86:
	dotnet publish PutProduct/PutProduct.csproj -c Release -r linux-x64 --self-contained -o $(ARTIFACTS_DIR)

build-DeleteProductFunctionX86:
	dotnet publish DeleteProduct/DeleteProduct.csproj -c Release -r linux-x64 --self-contained -o $(ARTIFACTS_DIR)