version: 0.2

phases:
  install:
    commands:
      - npm i artillery -g
  build:
    commands:
      - export temp1=$(pwd);echo $temp1
      - cd loadtest/codebuild
      - ./run-all-load-tests.sh
artifacts:
  files:
    - src/NET6MinimalAPI/Report/*
    - src/NET6MinimalAPIWebAdapter/Report/*
    - src/NET8MinimalAPI/Report/*
  name: loadtest-$(date +%Y-%m-%H-%M) 