version: 0.2

phases:
  install:
    commands:
      - cd loadtest/codebuild
      - ./setup.sh
  build:
    commands:
      - ./run-all-load-tests.sh
artifacts:
  files:
    - src/NET6/Report/*
    - src/NET6Containers/Report/*
    - src/NET6CustomRuntime/Report/*
    - src/NET6MinimalAPI/Report/*
    - src/NET6MinimalAPIWebAdapter/Report/*
    - src/NET6TopLevelStatements/Report/*
    - src/NET6WithPowerTools/Report/*
    - src/NET8/Report/*
    - src/NET8MinimalAPI/Report/*
    - src/NET8Native/Report/*
    - src/NET8NativeMinimalAPI/Report/*
    - loadtestcli/Report/*
  name: loadtest-$(date +%Y-%m-%H-%M) 