AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  x86FunctionNamePrefix:
    Type: String
    Default: Net6-X86-powertools
  arm64FunctionNamePrefix:
    Type: String
    Default: Net6-Arm64-powertools
Globals:
  Function:
    MemorySize: 1024
    Runtime: dotnet6
    Timeout: 30
    Tracing: Active
    Environment:
      Variables:
        PRODUCT_TABLE_NAME: !Ref Table
        POWERTOOLS_METRICS_NAMESPACE: powertools-dotnet-benchmarking
        POWERTOOLS_SERVICE_NAME: powertools-dotnet-benchmarking
        POWERTOOLS_LOG_LEVEL: Debug
        POWERTOOLS_LOGGER_LOG_EVENT: true
        POWERTOOLS_LOGGER_CASE: SnakeCase

Resources:
  #X86
  GetProductsFunctionX86:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ -,[!Ref x86FunctionNamePrefix,GetProducts]]
      Architectures: [x86_64]
      CodeUri: ./GetProducts/
      Handler: GetProducts::GetProducts.Function::FunctionHandler
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /x86
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName:
              !Ref Table

  GetProductFunctionX86:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ -,[!Ref x86FunctionNamePrefix,GetProduct]]
      Architectures: [x86_64]
      CodeUri: ./GetProduct/
      Handler: GetProduct::GetProduct.Function::FunctionHandler
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /x86/{id}
            Method: GET
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: dynamodb:GetItem
              Resource: !GetAtt Table.Arn

  DeleteProductFunctionX86:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ -,[!Ref x86FunctionNamePrefix,DeleteProduct]]
      Architectures: [x86_64]
      CodeUri: ./DeleteProduct/
      Handler: DeleteProduct::DeleteProduct.Function::FunctionHandler
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /x86/{id}
            Method: DELETE
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
                - dynamodb:GetItem
              Resource: !GetAtt Table.Arn

  PutProductFunctionX86:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ -,[!Ref x86FunctionNamePrefix,PutProduct]]
      Architectures: [x86_64]
      CodeUri: ./PutProduct/
      Handler: PutProduct::PutProduct.Function::FunctionHandler
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /x86/{id}
            Method: PUT
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: dynamodb:PutItem
              Resource: !GetAtt Table.Arn
#ARM64
  GetProductsFunctionArm64:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ -,[!Ref arm64FunctionNamePrefix,GetProducts]]
      Architectures: [arm64]
      CodeUri: ./GetProducts/
      Handler: GetProducts::GetProducts.Function::FunctionHandler
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /arm64
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName:
              !Ref Table

  GetProductFunctionArm64:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ -,[!Ref arm64FunctionNamePrefix,GetProduct]]
      Architectures: [arm64]
      CodeUri: ./GetProduct/
      Handler: GetProduct::GetProduct.Function::FunctionHandler
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /arm64/{id}
            Method: GET
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: dynamodb:GetItem
              Resource: !GetAtt Table.Arn

  DeleteProductFunctionArm64:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ -,[!Ref arm64FunctionNamePrefix,DeleteProduct]]
      Architectures: [arm64]
      CodeUri: ./DeleteProduct/
      Handler: DeleteProduct::DeleteProduct.Function::FunctionHandler
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /arm64/{id}
            Method: DELETE
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
                - dynamodb:GetItem
              Resource: !GetAtt Table.Arn

  PutProductFunctionArm64:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ -,[!Ref arm64FunctionNamePrefix,PutProduct]]
      Architectures: [arm64]
      CodeUri: ./PutProduct/
      Handler: PutProduct::PutProduct.Function::FunctionHandler
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /arm64/{id}
            Method: PUT
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: dynamodb:PutItem
              Resource: !GetAtt Table.Arn

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
  ApiUrlX86:
    Description: "X86 API endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/x86"
  ApiUrlArm64:
    Description: "Arm64 GateAPI endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/arm64"
  
  #x86
  LambdaX86NameGetProducts:
    Description: "Lambda X86 GetProducts"
    Value: !Join [ -,[!Ref x86FunctionNamePrefix,GetProducts]]
  LambdaX86NameGetProduct:
    Description: "Lambda X86 GetProduct"
    Value: !Join [ -,[!Ref x86FunctionNamePrefix,GetProduct]]
  LambdaX86NameDeleteProduct:
    Description: "Lambda X86 DeleteProduct"
    Value: !Join [ -,[!Ref x86FunctionNamePrefix,DeleteProduct]]
  LambdaX86NamePutProduct:
    Description: "Lambda X86 PutProduct"
    Value: !Join [ -,[!Ref x86FunctionNamePrefix,PutProduct]]
  
  #arm64
  LambdaArm64NameGetProducts:
    Description: "Lambda X86 GetProducts"
    Value: !Join [ -,[!Ref arm64FunctionNamePrefix,GetProducts]]
  LambdaArm64NameGetProduct:
    Description: "Lambda X86 GetProduct"
    Value: !Join [ -,[!Ref arm64FunctionNamePrefix,GetProduct]]
  LambdaArm64NameDeleteProduct:
    Description: "Lambda X86 DeleteProduct"
    Value: !Join [ -,[!Ref arm64FunctionNamePrefix,DeleteProduct]]
  LambdaArm64NamePutProduct:
    Description: "Lambda X86 PutProduct"
    Value: !Join [ -,[!Ref arm64FunctionNamePrefix,PutProduct]]