name: "SAM Build & Deploy"
description: "Build & Deploy SAM application"
inputs:
   aws-access-key:
     required: true
     description: "AWS Access Key"
   aws-secret-key:
     required: true
     description: "AWS Secret Key"
   aws-region:
     required: true
     description: "AWS Region"
   dotnet-version:
     required: true
     description: ".NET Version to configure"
   template-file-path:
     required: true
     description: "Path to the SAM template file"
   project-directory:
     required: true
     description: "Path to the directory containing the .NET project file"
   stack-name:
     required: true
     description: "The name of the CloudFormation stack to deploy"
   s3-bucket-name:
     required: true
     description: "The name of the S3 bucket to store SAM artifacts"

runs:
  using: "composite"
  steps:
    # Python is already installed on our custom runner, and this GitHub action to install python doesn't understand AL2023 ARM
    # - uses: actions/setup-python@v2
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    - uses: aws-actions/setup-sam@v2
      with:
          use-installer: false # use-installer Currently supports Linux x86-64 runners. https://github.com/aws-actions/setup-sam?tab=readme-ov-file#inputs
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_SAM_DEPLOYMENT_ROLE }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ secrets.AWS_REGION }}
    
# Build and deploy ARM
    # Because native apps are built in a container, and SAM CLI doesn't know how to mount extra things outside the project directory to the container, move this file manually
    - run: cp Directory.Build.props ${{ inputs.project-directory }}/Directory.Build.props
      shell: bash
    - run: export PATH="$PATH:/home/ec2-user/.dotnet/tools" && sam build -t ${{ inputs.template-file-path }} --parameter-overrides LambdaArchitecture=arm64
      shell: bash
    - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ${{inputs.stack-name}}-arm64 --s3-prefix ${{inputs.stack-name}}-arm64 --s3-bucket ${{ inputs.s3-bucket-name }} --capabilities CAPABILITY_IAM --parameter-overrides LambdaArchitecture=arm64
      shell: bash