build-MinimalApiX86:
	dotnet publish ApiBootstrap/ApiBootstrap.csproj -c Release -r linux-x64  -o $(ARTIFACTS_DIR)
build-MinimalApiArm64:
	dotnet publish ApiBootstrap/ApiBootstrap.csproj -c Release -r linux-x64 -o $(ARTIFACTS_DIR)