name: testingCodeBuild NET 8 NativeAOT Canary

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  schedule:
  # Run this once a day to check if everything is still working as expected.
    - cron: "30 23 * * *"

jobs:

  build-deploy:
      runs-on: codebuild-NativeAotCanaryCustomGitHubRunner-${{ github.run_id }}-${{ github.run_attempt }}
      steps:
        - uses: actions/checkout@v2  
        - name: Build and Deploy
          uses: ./.github/actions/sam-build-and-deploy-native
          with:
            aws-role: ${{ secrets.AWS_SAM_DEPLOYMENT_ROLE }}
            aws-region: ${{ secrets.AWS_REGION }}
            dotnet-version: '8.x'
            template-file-path: ./src/NET8Native/template.yaml
            project-directory: ./src/NET8Native/
            stack-name: net-8-native
            s3-bucket-name: aws-dotnet-lambda-testing

  build-deploy-arm:
      # This needs to run on our custom runner which supports ARM. The runner is an EC2 instance manually 
      # configured in the same AWS account.
      runs-on: [self-hosted, ARM64]
      steps:
        - uses: actions/checkout@v2  
        - name: Build and Deploy ARM
          uses: ./.github/actions/sam-build-and-deploy-native-arm
          with:
            aws-role: ${{ secrets.AWS_SAM_DEPLOYMENT_ROLE }}
            aws-region: ${{ secrets.AWS_REGION }}
            dotnet-version: '8.x'
            template-file-path: ./src/NET8Native/template.yaml
            project-directory: ./src/NET8Native/
            stack-name: net-8-native
            s3-bucket-name: aws-dotnet-lambda-testing

  load-test-x86:
      needs: build-deploy
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Run Load Tests
          uses: ./.github/actions/run-load-test
          with:
            api-endpoint: ${{ secrets.API_ENDPOINT_NET_8_NATIVE_X86 }}

  load-test-arm:
      needs: build-deploy-arm
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2  
        - name: Run Load Tests
          uses: ./.github/actions/run-load-test
          with:
            api-endpoint: ${{ secrets.API_ENDPOINT_NET_8_NATIVE_ARM }}
                
